version: '3.5'
services:
  iletters-admin-fe-dev:
    image: dev.registry.ii-ai.tech/${PROJECT_NAME}/${SERVICE_NAME}:${IMAGE_VERSION}
    networks:
      - ii-swarm-net
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s


networks:
  ii-swarm-net:
    external: true
