language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules

# 设置环境变量
env:
  matrix:
    - CI=true

script:
  # 运行部署脚本
  - npm run deploy

deploy:
  # 发布到 gh-pages 上
  - provider: script
    # Do not delete the build assets
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      # 当 master 有 push 的时候，触发 deploy 操作
      branch: master
